

SELECT E.ID, IFNULL(CHILD_COUNT, 0) CHILD_COUNT
FROM ECOLI_DATA E
LEFT JOIN (
    SELECT PARENT_ID, COUNT(*) CHILD_COUNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
) A ON E.ID = A.PARENT_ID
ORDER BY E.ID