-- 코드를 입력하세요
-- 1) 세단, SUV 중 대여 가능한 자동차 뽑기
-- 2) 30일 간 대여 금액이 50 ~ 200만원인 자동차 뽑기
# 계산할 때 조건에 따라 다르게 계산해야 하고
# 계산 결과가 조건에 맞는 경우만 선택해 출력해야 함

SELECT *
FROM 
(
SELECT B.CAR_ID, B.CAR_TYPE, 
    ROUND(DAILY_FEE  * 30 * (100 - DISCOUNT_RATE) / 100) AS FEE
FROM (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상'
) A
RIGHT JOIN 
(
    SELECT DISTINCT A.CAR_ID, CAR_TYPE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR A
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    ON A.CAR_ID = B.CAR_ID
    WHERE CAR_TYPE IN ('SUV', '세단')
    AND A.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE START_DATE <= '2022-11-30'
            AND END_DATE >= '2022-11-01'
    )
) B
ON A.CAR_TYPE = B.CAR_TYPE
) D
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC

