-- 코드를 작성해주세요

SELECT FISH_COUNT, A.FISH_NAME
FROM FISH_NAME_INFO A
RIGHT JOIN
(SELECT COUNT(*) AS FISH_COUNT, FISH_TYPE
from FISH_INFO 
GROUP BY FISH_TYPE) B
ON A.FISH_TYPE = B.FISH_TYPE
ORDER BY 1 DESC;