# 2021에 가입한 회원 전체 찾기
# 이 회원들의 구매 내역 찾고 이를 년-월로 그룹화해 


# SELECT *
# FROM ONLINE_SALE O
# WHERE USER_ID IN (
#     SELECT USER_ID
#     FROM USER_INFO U
#     WHERE YEAR(JOINED) = 2021
# )

SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, 
    COUNT(DISTINCT O.USER_ID) PURCHASED_USERS, 
    ROUND(COUNT(DISTINCT O.USER_ID) / USER_COUNT, 1) PUCHASED_RATIO
FROM ONLINE_SALE O
JOIN (
    SELECT USER_ID, COUNT(USER_ID) OVER () USER_COUNT
    FROM USER_INFO U
    WHERE YEAR(JOINED) = 2021
) A ON O.USER_ID = A.USER_ID
GROUP BY DATE_FORMAT(SALES_DATE, '%y-%m')
ORDER BY YEAR, MONTH


