# 프론트엔드 스킬을 가진 개발자
WITH FRONT_SKILL AS (
    SELECT SUM(CODE) FRONT_CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)

SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS D, FRONT_SKILL F
WHERE (D.SKILL_CODE & F.FRONT_CODE) != 0
ORDER BY ID