# 레어인 아이템의 다음 업그레이드 가능한 모든 아이템의 정보 출력하기

SELECT A.ITEM_ID, ITEM_NAME, RARITY
FROM (
    SELECT T.ITEM_ID ITEM_ID
    FROM ITEM_INFO I
    LEFT JOIN ITEM_TREE T
    ON I.ITEM_ID = T.PARENT_ITEM_ID
    WHERE RARITY = 'RARE' AND T.ITEM_ID IS NOT NULL
) A
JOIN ITEM_INFO B ON A.ITEM_ID = B.ITEM_ID
ORDER BY ITEM_ID DESC