# 부모의 형질을 모두 보유한 대장균
# 부모의 형질과 자신의 형질을 AND 연산했을 때 부모 형질과 같은 값이 나와야 함

SELECT C.ID ID, C.GENOTYPE, P.GENOTYPE PARENT_GENOTYPE
FROM ECOLI_DATA C
JOIN ECOLI_DATA P
ON C.PARENT_ID = P.ID
WHERE P.GENOTYPE & C.GENOTYPE = P.GENOTYPE
ORDER BY ID