-- 코드를 작성해주세요
SELECT SCORE, E.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES E
JOIN (
    SELECT EMP_NO, SUM(SCORE) SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
    HAVING SUM(SCORE) =
    (   
        SELECT SUM(SCORE)
        FROM HR_GRADE
        GROUP BY EMP_NO
        ORDER BY 1 DESC
        LIMIT 1
    )
) A
ON E.EMP_NO = A.EMP_NO



