SELECT SCORE, EMP_NO, EMP_NAME, POSITION, EMAIL
FROM
(
SELECT E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL,
    SUM(G.SCORE) AS SCORE,
    RANK() OVER (ORDER BY SUM(G.SCORE) DESC) AS RK
FROM HR_EMPLOYEES E
JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO
GROUP BY E.EMP_NO
) A
WHERE RK = 1;